### ISSUE TITLE
Error command 'extension.connectMySQL' not found

### ISSUE THREAD

**Issue by k--kato** [Bajdzis/vscode-database#7]
vscode-database: v1.0.1
vscode: v1.7.1
OS: windows 10

Operation: 
1. Open `Command Palette`
1. Choose `SQL: Connect to MySQL Server`
1. `Error command 'extension.connectMySQL' not found`

![image](https://cloud.githubusercontent.com/assets/10364603/20374948/27d988fe-acbf-11e6-83b0-97ba5f8aca41.png)

**Comment by Bajdzis** [comment]
In my vs code works :(
Is only `SQL: Connect to MySQL Server` command does not work ?

**Comment by halldors** [comment]
Same for me, I get Error command '***' not found on all SQL commands.

**Comment by almeidafandre** [comment]
On macOS is the same error: "command 'extension.connectMySQL' not found"

**Comment by Bajdzis** [comment]
Everything works in `1.0.10` version :) Thank you to everyone for comments :)

**Comment by almeidafandre** [comment]
In my case it continues to give the same error in 1.0.10.

**Comment by pjam** [comment]
Same here

**Comment by Bajdzis** [comment]
@almeidafandre @pjam Please open Help > Toggle Developer Tools. Take a screenshot. Then send screenshot in issues.

**Comment by k--kato** [comment]
@Bajdzis 
What is your vsce version?  The current version is 1.17.0.

```bash
vsce --version
npm update -g vsce
vsce publish
```

**Comment by fenglinnet** [comment]
Same problem,

[Extension Host] Here is the error stack:  Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.W.d._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:19841)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pan/.vscode-insiders/extensions/bajdzis.vscode-database-1.0.10/node_modules/pg-pool/index.js:4:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.W.d._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:19841)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pan/.vscode-insiders/extensions/bajdzis.vscode-database-1.0.10/node_modules/pg/lib/pool-factory.js:3:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.W.d._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:19841)
    at Module.require (module.js:483:17)

**Comment by pjam** [comment]
Here it is

![image](https://cloud.githubusercontent.com/assets/850139/20431665/2bd3a2f8-ad93-11e6-8c0b-ab3ad8b50f51.png)

**Comment by turtuga** [comment]
in file extension\engine\postgresql.js comment line `var pg = require('pg');` avoid this error

**Comment by turtuga** [comment]
After this in folder node_modules\mysql\node_modules\readable-stream 

run command 
`npm update --save`

and all works :)

**Comment by Bajdzis** [comment]
Sorry all is my fault.  I had old version `vsce`. 
version `1.0.11` should work.

Thanks for help @turtuga, @k--kato :)

**Comment by turtuga** [comment]
@Bajdzis thanks

**Comment by k--kato** [comment]
@Bajdzis It works! Thnaks!
